export const users = [
    {
        name:"Jay",
        descr:"Student",
        img:"/vercel.svg"
    },
    {
        name:"Jay",
        descr:"Student",
        img:"/vercel.svg"
    },
    {
        name:"Jay",
        descr:"Student",
        img:"/vercel.svg"
    },
    {
        name:"Jay",
        descr:"Student",
        img:"/vercel.svg"
    },
    {
        name:"Jay",
        descr:"Student",
        img:"/vercel.svg"
    },
    {
        name:"Jay",
        descr:"Student",
        img:"/vercel.svg"
    },
    {
        name:"Jay",
        descr:"Student",
        img:"/vercel.svg"
    },
    {
        name:"Jay",
        descr:"Student",
        img:"/vercel.svg"
    },
    {
        name:"Jay",
        descr:"Student",
        img:"/vercel.svg"
    },
]